### ISSUE TITLE
看到的散了吧..

### ISSUE THREAD

**Issue by zizhilong** [lmx1989219/goexchange#3]
作者写的这个程序.是基于大智慧内部框架做得开发,缺的库并不开源..
嗯.第二个问题如果作者能看得到的话可以讨论下.MatchList的算法优化似乎不太好.是否考虑使用container\heap小根堆来排序.否则如果出现卖价很高,或者买价很低,优化不太够吧.

**Comment by zizhilong** [comment]
15904261873有兴趣可以加微信

**Comment by alansfa** [comment]
@zizhilong 我已经没研究golang啦。抱歉哈
