### ISSUE TITLE
请问如何使用呢？

### ISSUE THREAD

**Issue by ygcool** [lmx1989219/goexchange#7]
我目前是用php开发前台接口。如果要把用户下单数据接入到这个撮合服务，该如何操作呢？

**Comment by alansfa** [comment]
用protobuf协议对接，这个项目只是核心逻辑实现。有些底层的外部依赖不太方便放进来。



---原始邮件---
发件人: "ygcool"<notifications@github.com&gt;
发送时间: 2019年9月11日(星期三) 中午12:03
收件人: "lmx1989219/goexchange"<goexchange@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lmx1989219/goexchange] 请问如何使用呢？ (#7)



我目前是用php开发前台接口。如果要把用户下单数据接入到这个撮合服务，该如何操作呢？
